### ISSUE TITLE
Increase the resource limit per stack

### ISSUE THREAD

**Issue by hoegertn** [aws-cloudformation/aws-cloudformation-coverage-roadmap#108]
It would really be great to have more than 200 resources in one CFN stack. 

Especially, with CDK or SAM it is hard to estimate the number of resources that are being created.

**Comment by benkehoe** [comment]
In some ways, I think this is a similar question as Lambda timeouts: for any given limit, there are going to be people who want a higher limit. At some point, a line should be drawn and better alternatives should be promoted instead of continually allowing people to simply dump more resources into the same stack. Improvements to nested stacks could help, for example. Such alternatives could then be leveraged by SAM and CDK to better manage the generated resources they create.

I'm not arguing that 200 is the right limit, just that we should mindful of what raising the limit means.

**Comment by hoegertn** [comment]
I totally agree but 200 seems very low when you look at serverless APIs I think. Having a resource, method, lambda, invoke permission, several alarms, IAM role, etc for each endpoint sums up very fast.

**Comment by j0b0sapi3n** [comment]
+1 for increasing the 200 resource limit

**Comment by PatMyron** [comment]
merging limit issues into https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/360
