### ISSUE TITLE
AWS::SSM::Document-NewAttribute (Name)

### ISSUE THREAD

**Issue by azec-pdx** [aws-cloudformation/aws-cloudformation-coverage-roadmap#115]
## 1. Title 
AWS::SSM::Document-NewAttribute

## 2. Scope of request 
`AWS::SSM:Document` supports `Content`, `DocumentType` and `Tags` as only properties as of today per [documentation provided](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-document.html). It would be great to provide `Name` property which allows organizations to use own schema for SSM Documents naming when managing multiple SSM Documents stacked through CloudFormation. This allows orgs to easier find documents when executing Automation or using Run Document feature. 

That would also make it consistent with aws cli [create-document](https://docs.aws.amazon.com/cli/latest/reference/ssm/create-document.html) and SSM [CreateDocument API](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_CreateDocument.html#API_CreateDocument_RequestSyntax) , which both have `--name` , or [Name](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_CreateDocument.html#systemsmanager-CreateDocument-request-Name) , respectively as required property. 

#### in Create 
of the `AWS::SSM:Document`, for the first time, if the resource has attribute `Name` , then that document should be stacked in AWS Systems Manager under name provided as value. If the document with existing name already exists, CF stacking operation should fail and rollback with proper error. 

Currently the CloudFormation gives SSM document computed name in format:
<STACK_NAME>-<CF_LOGICAL_RESOURCE_NAME>-<SOME_CF_HASH>
Example of this: if I stacked `infrastructure-mongo-Resources` stack and within I have `SSMRunCommandDocumentSynctoolLXQA` resource of type `AWS::SSM::Document`, then CloudFormation computes name of the document as `infrastructure-mongo-Resources-SSMRunCommandDocumentSynctoolLXQA-AEB6RQHJWFXH` in Systems Manager. This is hard to search for and get used to.

#### in Update 
of the `AWS::SSM::Document`, current behavior is such that CF updates always same version of the SSM Document which remains DEFAULT version if it hasn't been manually changed in AWS Console or via [update-document-version](https://docs.aws.amazon.com/cli/latest/reference/ssm/update-document-default-version.html) API. This means that any update on the `Content` attribute of the `AWS::SSM::Document` resource doesn't yield to creating new version of the document which is very positive. 
Unless the attribute `Name` is changed on `AWS::SSM:Document` resource, only document content should be updated. If the `Name` attribute is changed on `AWS::SSM::Document` resource it should cause the replacement of the resource, with new SSM Document being stacked under new name and then previous document deleted. If another document already exists under new (updated) name, then CloudFormation should fail early without deleting SSM Document which existed under old name (before attempt to update).

#### in Delete
behavior should be simple - just delete regardless of the `Name` attribute value

#### Common use case: 

- [ ]  if `Name` attribute is passed on `AWS::SSM:Document` resource, then in AWS Systems Manager console under **Documents** section it should be searchable under that name.

## 5. Helpful Links to speed up research and evaluation
* https://docs.aws.amazon.com/cli/latest/reference/ssm/update-document-default-version.html
* https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_CreateDocument.html#systemsmanager-CreateDocument-request-Name

## 6. Category

Management & Governance ( Systems Manager)

## 7. Any additional context (optional)

This prevents us from versioning SSM documents as IaaC and easily documenting workflows that use Automation and Run Command features of SSM as we have to link docs to specific documents stacked with CloudFormation vs. just stating their name based on what they are intended for.

**Comment by jk2l** [comment]
hi @luiseduardocolon I think the implementation is incorrect corresponding to the ticket original request.

Current behaviour:
- When SSM Document updated, it will trigger a replacement
- If we use hardcode Name, stack update will fail with the message "GoldenAMIAutomationDoc AWS::SSM::Document UPDATE_FAILED CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename GoldenAmiBuidler and update the stack again."

Expected behaviour:
- Originally described in the ticket: a new version created and on success it should update the current version to Default.
- For reference can also look into how AWS::SSM::Parameter is done, it will update and create a new version instead of replacing the document completely. 

Currently, I have to create/manage a custom resource just to do this behaviour but maintaining the Custom resource is quite time-consuming for me and I wish i can replace my custom resource to be using native AWS resources only. 

The key part of this request is we can have versioning of the AWS SSM Document that we can also reference back into. 

As a use case, I have to follow a very strict security audit process (the operation team do not have security clearance to touch production environment. Everything is 100% manage by CloudFormation. or it will need to escalate to system admin that have access which can also costly to do) and the SSM Doc native implementation by CloudFormation is very badly design because it lost the versioning refrence which fail auditing process. 

Currently I am using SSM for the following:
- AMI Builder
- System patches
- AWS Inspector
- Some installation and automation

**Comment by jk2l** [comment]
@luiseduardocolon I have created a new request as this is marked as Closed
