### ISSUE TITLE
AWS::S3::Bucket - (new property) Object Lock 

### ISSUE THREAD

**Issue by TheDanBlanco** [aws-cloudformation/aws-cloudformation-coverage-roadmap#13]
Quick Sample Summary:
1. Title -> AWS::S3::Bucket - (new property) Object Lock 
2. Scope of request -> AWS::S3::Bucket - buckets should support object lock configurations, to allow a Write Once Read Many (WORM) model. 
3. Expected behavior -> When a user creates a bucket with an Object Lock Policy, it should no longer be writable but still continue to be readable
4. Test case recommendation (optional) -> once a bucket is created and locked, it should no longer be writable
5. Links to existing API doc (optional) -> https://docs.aws.amazon.com/cli/latest/reference/s3api/put-object-lock-configuration.html
6. Category tag (optional) -> Storage
7. Any additional context (optional)

**Comment by jthomerson** [comment]
Since followers just get an email saying this is closed, it's a bit hard to determine the reason it's closed. Thus, including a link to the new feature - IOW, this is supported now: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html#cfn-s3-bucket-objectlockconfiguration
