### ISSUE TITLE
AWS::ElasticLoadBalancingV2::ListenerRule - Arbitrary header based routing

### ISSUE THREAD

**Issue by TheDanBlanco** [aws-cloudformation/aws-cloudformation-coverage-roadmap#22]
1. Title -> AWS::ElasticLoadBalancingV2::ListenerRule - Arbitrary header based routing
2. Scope of request -> ELB recently announced support for arbitrary header based routing and CloudFormation support should follow
3. Expected behavior -> When creating a Listener Rule in CloudFormation, we should be able to specify arbitrary header based routing conditions
4. Test case recommendation (optional) -> 
5. Links to existing API doc (optional) -> https://docs.aws.amazon.com/cli/latest/reference/elb/create-load-balancer-listeners.html
6. Category tag (optional) -> Networking
7. Any additional context (optional)

**Comment by jthomerson** [comment]
I think this may be a more accurate API doc link: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html#rule-condition-types

Here's the link to support "recently announced": https://aws.amazon.com/blogs/aws/new-advanced-request-routing-for-aws-application-load-balancers/

Hope that helps.

**Comment by jthomerson** [comment]
Since followers just get an email saying this is closed, it's a bit hard to determine the reason it's closed. Thus, including a link to the new feature - IOW, this is supported now:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-listenerrule-conditions.html

See "HttpHeaderConfig"
