### ISSUE TITLE
AWS::Config::OrganizationConfigRule - new resource

### ISSUE THREAD

**Issue by algra** [aws-cloudformation/aws-cloudformation-coverage-roadmap#46]
1. Title -> AWS::Config::OrganizationConfigRule
2. Scope of request -> Can create resource via API, but not via CloudFormation.
3. Expected behavior -> Should be possible to create, update and delete organization config rules as API supports.
4. Test case recommendation (optional)
5. Links to existing API doc (optional) -> https://docs.aws.amazon.com/config/latest/APIReference/API_PutOrganizationConfigRule.html & https://docs.aws.amazon.com/config/latest/APIReference/API_DeleteOrganizationConfigRule.html
6. Category tag (optional) -> Management

**Comment by atkinsonm** [comment]
Resolved in the August 29 release: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html

**Comment by citrusoft** [comment]
Resolved?  kinda, I have been successfully using AWS::Config::OrganizationConfigRule to create stacks of AWS Managed Config Rules.  However, I am unable to deploy Custom Config Rules.  Can anyone share a URL to CloudFormation template(s) that deploy Custom organization-config-rule with its dependencies?
Also, how do you setup a service-role to create such stacks?

**Comment by luiseduardocolon** [comment]
Closing this issue since this is already supported for both managed and custom config rules.  There are samples for both here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-config-organizationconfigrule.html
If you'd like, you may request another/different sample for this particular doc page by using the Feedback link.
