### ISSUE TITLE
AWS::IAM::OpenIDConnectProvider

### ISSUE THREAD

**Issue by errordeveloper** [aws-cloudformation/aws-cloudformation-coverage-roadmap#53]

**Comment by TheDanBlanco** [comment]
Can you please fill out the issue template? It really helps us be able to prioritize the work.

**Comment by dnascimento** [comment]
## 1. Title 
AWS::IAM::OpenIDConnectProvider

## 2. Scope of request 
A new resource type for an existing service is desired. IAM exists but does not support `OpenIDConnectProvider`

This can be created via API but not via CloudFormation.

## 3. Expected behavior

Invoke the existing API to create an OpenIDConnectProvider

## 4. Suggest specific test cases

Common use case: create an OpenIDConnectProvider with a thumbprint, url and client-list (optional)

## 5. Helpful Links to speed up research and evaluation

[create-open-id-connect-provider](https://docs.aws.amazon.com/cli/latest/reference/iam/create-open-id-connect-provider.html)
[via CLI/UI/API](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html)

## 6. Category

8. Security (IAM, KMS...)

## 7. Any additional context (optional)
