### ISSUE TITLE
AWS::Route53::RecordSet should allow to be imported into a new stack

### ISSUE THREAD

**Issue by OlafConijn** [aws-cloudformation/aws-cloudformation-coverage-roadmap#560]
Quick Sample Summary:

> I would expect resources of type `AWS::Route53::RecordSet` to be importable using CloudFormation 

Category (required) - Will help with tagging and be easier to find by other users to +1

> Networking & Content (VPC, Route53, API GW,...)

**Comment by PatMyron** [comment]
more generally tracking in https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/276

As [CloudFormation Registry](https://aws.amazon.com/blogs/aws/cloudformation-update-cli-third-party-resource-support-registry/) types [now automatically support resource import operations](https://aws.amazon.com/about-aws/whats-new/2020/06/aws-cloudformation-resource-import-supports-cloudformation-registry-types/), a [migration of this type to the newer Registry framework](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-route53/pull/3) should pick this up automatically

**Comment by pmmsignify** [comment]
This should not be closed. AWS::Route53::RecordSet is still not importable:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html

**Comment by AlecZebrick** [comment]
+1 just came across this myself

**Comment by benbridts** [comment]
For anyone stumbling on this issue, there is a workaround for "simple" records:

1. In the old stack: make every record a weighted records with (eg) weight 1 and AWS::StackName as SetIdentifier
2. In the new stack: create a new resource that's exactly the same as the old stack (same weight, AWS::StackName as identifier)
3. Remove the record from the old stack
4. Make the record in the new stack a simple record

**Comment by benbridts** [comment]
@AlecZebrick You should be able to make them weighted with the CLI or console (and use e.g. "manual" as SetIdentifier)

I would like every resource to be supported by imports, but AWS teams have to do a migration for older resources to get there (not sure why they were working on that in 2022 and it has not been deployed yet)

**Comment by Patryk803** [comment]
+1 we can't wait once this feature will be available.

**Comment by Chipster338** [comment]
Work at AWS support here, even though this github is closed, there is an internal feature request open for this.
As a workaround that worked in my testing:
Let's say you have a hosted zone in console which has records in it and you want to import this into a cloudformation template.
You first need to import the hosted zone. A stack and a template gets generated out of it. The records are not in that template yet.
Then you need to update the stack and you need to add the exact records that are in the console. Cloudformation will not create new records and it will not fail (on existing records already), it will 'import' them into the stack.

You can use Former2 tool to get the exact resource infrastructure of the records.

**Comment by Luchiap** [comment]
@garrethmcdaid-zd this did not happen to me, nor my support client at the time.
You have to be super sure you are using the exact resource information of the existing records. Have you used former2?

**Comment by garrethmcdaid-zd** [comment]
@Luchiap Can you confirm you used the CLI `update-stack` operation when doing this?

I'm just can't error messages to state that the records already exist.

**Comment by andrej-p** [comment]
Just to share - I have the similar situation - I need to start managing a route53 zone with CFN. 

I have created a template file with all the resource records I want to add to the CFN stack (just a subset of the actual records in the actual zone - the rest of the records are either SOA, NS, or ACM verification records, or records managed in other stacks, so I did not need to add them). 

During my testing in one domain I was able to just run the stack creation without importing the zone, and all the records (which already existed in the zone and were defined in the template) were successfully added to the stack and I could have kept managing them through CFN.

In other domain I experienced an issue that the `www.domain.tld` CNAME could not have been created - it failed with `[Tried to create resource record set [name='www.domain.tld.', type='CNAME'] but it already exists]`. 
Then it deleted all the entries that I tried to "import" from the actual zone 😓 

Please use `DeletionPolicy: Retain` while working on this 😄 

I've tried creating the stack with "Preserve successfully provisioned resources", which has "imported" the resources, but has left the stack in the `CREATE_FAILED` state. I was then able to delete the resources that were not successfully "created" from the zone, and have been able to run the stack update which has created them without issues. This is not cool because of the downtime while they get recreated.

I've then tried recreating the stack from scratch, and...it has successfully "imported" all the resources! :exploding: I guess that something was broken around that `www.domain.tld` entry from the tests I ran, so that is cool! 

So, the whole process here was:
1. add the ResourceRecords I want to manage to the template with `DeletionPolicy: Retain`
2. run a creation of the new stack, which did not delete any existing stack, it just enabled managing them through CFN

I like CFN more and more, to be honest.

**Comment by luk2302** [comment]
What @Luchiap wrote is correct: CloudFormation will allow you to auto-import existing records IFF the record is absolutely identical. This means the type, the name, the value and even the TTL need to match. 
Then CF will internally do 4 things:
* issue a ChangeResourceRecordSets call to create the record - this call will fail because the record already exists
* issue a ListResourceRecordSetsInfo call to get the current record
* compare the retrieved record with the desired record and only if they match will it continue to
* issue a second ChangeResourceRecordSets with a DELETE and a CREATE action for the same record explaining in the comment of the API call "Making no-op change to get a ChangeId"

You can double-check all that using CloudTrail. 

After this CF now knows and tracks the record and can from now on update and also delete the record(s). This means the record(s) is actually a resource for which CF supports an auto-import feature, without actually supporting a manual import.

**Comment by ansraliant** [comment]
Jumping in just to thanks @luk2302 and @Luchiap for their help.

I was trying to import a RecordSet and failed due to the same reasons described in this issue, and despite it being closed, thanks to the suggestions of both I could import the resource and start track it with CDK.

I hope we can have a manual import and not a hackish solution like this one.

**Comment by iDVB** [comment]
Can we get an example of what these templates might look like? 
This process isn't working for us. We're still getting the error 
`[Tried to create resource record set [name='appliedsciences.klick.com.', type='A'] but it already exists]`

## Reproduction Steps

1. Add existing HostedZone to template with "Retain" DeletionPolicy
```
  HostedZone1234:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: "Retain"
    Properties:
      Name: nottelling.domain.com
```

1. Use Former2 to describe the existing RecordSets
```
    Route53RecordSet:
        Type: "AWS::Route53::RecordSet"
        Properties:
            Name: !Ref Route53RecordSet2
            Type: "A"
            AliasTarget: 
                HostedZoneId: "Z2FDTNDATAQYW2"
                DNSName: "nottelling.cloudfront.net."
                EvaluateTargetHealth: false
            HostedZoneId: "EXAMPLE_1"

    Route53RecordSet2:
        Type: "AWS::Route53::RecordSet"
        Properties:
            Name: "nottelling.domain.com."
            Type: "AAAA"
            AliasTarget: 
                HostedZoneId: "Z2FDTNDATAQYW2"
                DNSName: "nottelling.cloudfront.net."
                EvaluateTargetHealth: false
            HostedZoneId: "EXAMPLE_1"
```

3. Translate to the desired LogicalId into template. Notice `EvaluateTargetHealth` is new from Former2 also we're NOT referencing the `HostedZone1234` to put the `HostedZoneId` into the RecordSets... not sure if that is needed. If not, not sure what the point of adding the HostedZone1234 is even is?
```
  HostedZone1234:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: "Retain"
    Properties:
      Name: nottelling.domain.com
  NextJsSiteAliasRecord3E1A747A:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      Name: nottelling.domain.com.
      Type: A
      AliasTarget:
        DNSName: !GetAtt 
          - NextJsSiteDistribution2961ED05
          - DomainName
        HostedZoneId: !FindInMap 
          - AWSCloudFrontPartitionHostedZoneIdMap
          - !Ref 'AWS::Partition'
          - zoneId
        EvaluateTargetHealth: false
      HostedZoneId: EXAMPLE_1
  NextJsSiteAliasRecordAAAA4DFAF164:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      Name: nottelling.domain.com.
      Type: AAAA
      AliasTarget:
        DNSName: !GetAtt 
          - NextJsSiteDistribution2961ED05
          - DomainName
        HostedZoneId: !FindInMap 
          - AWSCloudFrontPartitionHostedZoneIdMap
          - !Ref 'AWS::Partition'
          - zoneId
        EvaluateTargetHealth: false
      HostedZoneId: EXAMPLE_1
```

This still nets out with the CFN error of:
`[Tried to create resource record set [name='appliedsciences.klick.com.', type='A'] but it already exists]`

**Comment by cyounkins** [comment]
It took me awhile to get this to work, turns out the issue was that I had
`DNSName: !GetAtt CloudFrontDistribution.DomainName`
But the comparison requires the trailing period, so this worked:
`DNSName: !Sub "${CloudFrontDistribution.DomainName}."`

The `Name` in Route53 also has a trailing period, but this didn't seem to matter for the import in CFN.

**Comment by grayburnd** [comment]
How are we in 2025 and we still can't import the AWS::Route53::RecordSet Resource Type! This is crucial to allow flexibility with IaC setups for this critical resource. Please add this ASAP!

**Comment by andrej-p** [comment]
If it helps - you can *kind of* import the records by creating the new ones through cloudformation, which overwrite the manually created ones - as long as the TTL, Name, and ResourceRecords are exactly the same (with trailing dots, or lack of the same).

**Comment by markusl** [comment]
Confirming Luchiap's workaround works, with one extension and an apparent contradiction worth flagging.
  
 We tested this end-to-end on against a plain non-alias NS AWS::Route53::RecordSet (TTL + ResourceRecords, no AliasTarget, no SetIdentifier, no routing policy) in our own  hosted zone. The scenario was a logical-ID rename of an already-CloudFormation-managed record which is a slightly different shape from Luchiap's "adopt an unmanaged record" case, but the same underlying mechanism: a CloudFormation CREATE change action against a (HostedZoneId, Name, Type) tuple that already has a live RRset.

  Reproduction:

```
  # Starting state: stack contains a managed AWS::Route53::RecordSet
  # (Type: NS, Name: subdomain.example.com, with TTL + ResourceRecords)

  # 1. Add DeletionPolicy: Retain to the existing resource, deploy.
  #    -> In-place attribute update. No Route53 API calls. Live DNS unchanged.

  # 2. Remove the resource from the template, deploy.
  #    -> CloudFormation reports DELETE_SKIPPED on the resource.
  #    -> Live RRset stays in Route53 (verified via
  #       `aws route53 list-resource-record-sets` and `dig NS subdomain.example.com`).

  # 3. Re-add the resource under a NEW logical ID with identical
  #    HostedZoneId, Name, Type, TTL, and ResourceRecords, deploy.
  #    -> CREATE_COMPLETE. No "...already exists" error.
  #    -> `cdk diff` afterward is empty. No DNS resolution gap at any point.
```

  The new logical ID now owns the live record. This empirically confirms that the create handler for this RecordSet shape issues a Route53 UPSERT (idempotent when the values match  exactly), not a strict CREATE.

  Two things worth noting on top of that:                                                                                                                                

  1. The workaround is stronger than originally documented here. It handles not just adopting unmanaged records into a stack, but also renaming the logical ID of an already-managed record  via the retain-then-drop-then-readd sequence above. That matters because AWS::Route53::RecordSet is not in the CloudFormation import-supported resource list  (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html) (which contains Route53 HostedZone, CidrCollection, DNSSEC, HealthCheck, KeySigningKey, but neither RecordSet nor RecordSetGroup), so cdk import / cdk refactor are not available — this sequence is currently the only path.                   
  2. Apparent contradiction with the AWS KB. The article Resolve Route 53 errors in CloudFormation (https://repost.aws/knowledge-center/cloudformation-resolve-route53-errors) documents an "...already exists" failure when creating an AWS::Route53::RecordSet whose name/type already exists. Re-reading it carefully, every concrete example is an alias record (A/CNAME with AliasTarget). Our result suggests the strict-CREATE behavior described there may be alias-specific, while non-alias records use UPSERT. We did not test alias / plain A / CNAME / TXT /  MX shapes — we don't know whether those behave the same way as the NS case above.
  
  Two questions for the AWS team:

  - Is there any official documentation of the AWS::Route53::RecordSet create-handler semantics per record shape (UPSERT vs strict-CREATE, and which attributes flip it)? If yes, a link would help; if not, would AWS consider documenting it? Right now the behavior is empirically reliable but effectively folk knowledge.
  - Given that this works, would AWS consider either documenting the retain-drop-readd workaround as a supported pattern, or adding AWS::Route53::RecordSet (and AWS::Route53::RecordSetGroup) to the import-supported resource list so cdk import / cdk refactor work and this stops needing a workaround at all?

Either outcome would close a long-standing gap for everyone trying to bring existing Route53 records under CloudFormation management.
